---
title: "Water Availability Screening Tool"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    logo: www/DWR-ENF-Logo-48px.png
runtime: shiny
---

```{r setup, include=FALSE}

# Load libraries.
library(shiny)
library(flexdashboard)
library(sf)
library(leaflet)
library(dplyr)
library(wesanderson)
library(ggplot2)
library(aws.s3)

## Initialize values. ---

load_from_s3 <- FALSE

## Load data files. ----

if(load_from_s3) {
  # Water Right Info.
  s3load(object = "dwast-wrinfo.RData",
         bucket = "dwr-enf-shiny")
  
  # Demand Data.
  s3load(object = "dwast-demands.RData",
         bucket = "dwr-enf-shiny")
} else {
  # Water Right Info.
  load("./output/dwast-wrinfo-2020-12-18.RData")
  
  # Demand Data.
  load("./output/dwast-demands-2020-12-15.RData")
}

## Define color palettes and plot order. ----

# Water right type.
wr_type_pal <-colorFactor(c(wes_palette("Darjeeling1"), 
                            wes_palette("Darjeeling2"))[1:9],
                          pods$wr_type)

# Water availability demand.
wa_demand_order <- ordered(
  c("Junior Post-14",
    "Post-14",
    "Statement Demand",
    "Environmental Demand")
)
wa_demand_pal <- wes_palettes$GrandBudapest1[c(2, 1, 4, 3)]
names(wa_demand_pal) <- wa_demand_order

```

## Inputs {.sidebar}
-------------------------------------

```{r}
## Inputs. ----

# Choose how to visualize demand. By priority allows you to see supply data.
# Select watershed to view. <- TO DEVELOP
# radioButtons(inputId = "demand_display_selected",
#             label = "Select How To Display Demand:",
#             choices = c("By Priority\n(Includes Supply Forecast Where Available)" = "by_priority",
#                         "By Water Right Type" = "by_type"))

## Select HUC-8 watershed.
selectInput(inputId = "huc8_selected",
            label = "Select HUC-8 Watershed:",
            choices = sort(names(demand)),
            selected = sample(unique(names(demand)), 1),
            multiple = FALSE)

# Grab demand and wr_info for selected HUC-8.
ws_demand <- reactive({
  req(input$huc8_selected)
  demand[[input$huc8_selected]]
})
ws_wr_info <- reactive({
  req(input$huc8_selected)
  filter(wr_info, huc8_name %in% input$huc8_selected)
})

## Select Demand Scenario(s).
selectizeInput(inputId = "scenario_selected",
           label = "Select Up To Two Demand Scenarios:",
           choices = NULL,
           selected = NULL,
           multiple = TRUE,
           options = list(maxItems = 2))
 observeEvent(input$huc8_selected, {
              choices <- sort(na.omit(unique(ws_demand()$scenario)))
              updateSelectizeInput(session, "scenario_selected",
                                choices = choices,
                                selected = "Reported Diversions - 2019")
              })
scenario_demand <- reactive({
   req(input$scenario_selected)
   filter(ws_demand(), scenario %in% input$scenario_selected)
 })
scenario_wr_info <- reactive({
   req(input$scenario_selected)
   filter(ws_wr_info(), scenario %in% input$scenario_selected)
 })

## Select priority year to slice.
selectInput(inputId = "priority_selected",
           label = "Select Priority Year:",
           choices = NULL,
           selected = NULL,
             multiple = FALSE)
observeEvent(input$scenario_selected, {
  req(input$scenario_selected)
            choices <- sort(na.omit(unique(scenario_demand()$p_year)), decreasing = TRUE)
            updateSelectInput(session, "priority_selected",
                              choices = choices,
                              selected = max(scenario_demand()$p_year, na.rm = TRUE))
})


```

Column {data-width=600}
-------------------------------------

### Plot
```{r}
## Plot. ----
# Re-code fill_color based on selected priority.
plot_demand <- reactive({
  scenario_demand() %>% 
#    req(input$priority_selected)
    #   filter(huc8_name %in% input$huc8_selected) %>% 
    mutate(fill_color = if_else(priority == "Statement Demand",
                                "Statement Demand",
                                if_else(priority == "Statement Demand",
                                        "Statement Demand",
                                        if_else(p_year >= input$priority_selected,
                                                "Junior Post-14", "Post-14"))),
           fill_color = ordered(fill_color, levels = wa_demand_order)) %>% 
    group_by(scenario, rept_date, fill_color) %>% 
    summarise(demand_daily_af = sum(demand_daily_af, na.rm = TRUE),
              demand_daily_cfs = sum(demand_daily_cfs, na.rm = TRUE),
              .groups = "drop")
})

# Render the plot.
renderPlot({
  
  ggplot(data = plot_demand(),
         aes(x = rept_date,
             y = demand_daily_af,
             group = fill_color,
             fill = fill_color)) +
    geom_area(position = "stack") +
    scale_fill_manual(name = "Demand type:",
                      values = wa_demand_pal,
                      labels = c(paste(input$priority_selected, 
                                        "& Junior Post-14 Demand"),
                                 "Senior Post-14 Demand",
                                 "Statement Demand")) +
    labs(y = "Acre-Feet/Day") +
    theme(legend.position = "bottom",
          strip.text.x = element_text(size = rel(1.5)),
          axis.title = element_text(size = rel(1.2)),
          axis.text = element_text(size = rel(1.2)),
          legend.text = element_text(size = rel(1.2)),
          legend.title = element_text(size = rel(1.2)),
          axis.title.x = element_blank()) +
    facet_wrap(facets = vars(scenario),
               nrow = length(unique(plot_demand()$scenario)))
  
})

```

Column {data-width=400}
-------------------------------------

### Map {data-height=500}

```{r}
pod_points <- reactive({
  pods %>%
    filter(huc8_name %in% input$huc8_selected)
})

ws_poly <- reactive({
  huc8_layer %>% filter(huc8_name %in% input$huc8_selected)
})

renderLeaflet({
  validate(
    need(nrow(ws_poly()) > 0, 
         paste0("No Data Available.\n",
                "Please select another watershed."))
  )
  leaflet() %>%
    addProviderTiles(providers$CartoDB.Positron) %>%
    addPolygons(data = ws_poly(),
                weight = 2,
                col = "blue",
                fill = TRUE,
                fillOpacity = 0,
                label = ws_poly()$huc8_name,
                labelOptions = labelOptions(textsize = "12px",
                                            sticky = TRUE)) %>%
  addCircleMarkers(data = pod_points(),
                   radius = 3,
                   fillOpacity = 0.7,
                   stroke = TRUE,
                   color = ~wr_type_pal(wr_type),
                   weight = 1,
                   fillColor = ~wr_type_pal(wr_type),
                   label = pod_points()$wr_id) %>%
  addLegend(position = "topright",
            pal = wr_type_pal,
            values = pod_points()$wr_type,
            title = "Water Right Type",
            opacity = 1)
})
```   
 
### Demand Scenario Details {data-height=250}
    
```{r}
```


### Supply Scenario Details {data-height=250}
    
```{r}
```
