---
title: "Select Priority Year Prototype"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}

# Load libraries.
library(shiny)
library(flexdashboard)
library(dplyr)
library(wesanderson)
library(ggplot2)

load("./output/demand_test.RData")

# Create color palette for demand bins.
demand_order <- ordered(c("Junior Post-14",
                          "Post-14",
                          "Statement Demand",
                          "Environmental Demand"))
demand_pal <- wes_palettes$GrandBudapest1[c(2, 1, 4, 3)]
names(demand_pal) <- demand_order

```  

Inputs {.sidebar data-width=300}
-----------------------------------------------------------------------

```{r}
# Select/deselect HUC-8 watersheds.
selectInput(inputId = "priority_selected",
            label = "Select Priority Year:",
            choices = sort(na.omit(unique(demand_test$p_year)),
                           decreasing = TRUE),
            selected = max(demand_test$p_year, na.rm = TRUE),
            multiple = FALSE)
```  

Column {data-width=150 .tabset}
-----------------------------------------------------------------------

### Plot

```{r}



# Recode fill_color based on selected priority.
plot_demand <- reactive({
  mutate(demand_test,
         fill_color = if_else(priority == "Statement Demand", 
                              "Statement Demand", 
                              if_else(priority == "Statement Demand", 
                                      "Statement Demand", 
                                      if_else(p_year >= input$priority_selected, 
                                              "Junior Post-14", "Post-14"))),
         fill_color = ordered(fill_color, levels = demand_order))
})

# Render the plot. #######################
renderPlot({

  ggplot(data = plot_demand(),
            aes(x = as.factor(rept_month),
                y = demand,
                group = fill_color,
                fill = fill_color)) +
  geom_col(position = "stack") +
  scale_fill_manual(values = demand_pal)

})

```

### Water Right Info

### Statewide Watershed Map
